language: ruby
rvm:
- 2.3.3

script: bundle install && bundle exec jekyll build

exclude: [vendor]

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_GITHUB_TOKEN
  keep_history: true
  local-dir: ./_site
  target-branch: gh-pages
  on:
    branch: main

branches:
  only:
  - main